# Production docker-compose
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        GITHUB_TOKEN: '${GITHUB_TOKEN}'
        PROJECT_NAME: '${PROJECT_NAME}'
    ports:
      - '3000:3000'

  proxy:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    tty: true
