services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/opengine
      - pnpm-store:/root/.local/share/pnpm/store
    ports:
      - "3010:3010"
      - "3020:3020"
      - "3030:3030"
      - "3100:3100"
      - "3200:3200"
    env_file:
      - .env
    tty: true

volumes:
  pnpm-store:
